### ISSUE TITLE
[Programming] Auto Aimer Code

### ISSUE THREAD

**Issue by nick-mcgill** [FRC830/2024Robot#22]
Configure the auto aimer code on the robot to properly estimate the proper position and angle to shoot based on an update from the vision class.  See diagram by @Harsh-Sinha:
r = radius
t = time
v = velocity
![Image](https://github.com/FRC830/2024Robot/assets/13747745/b9a4f990-2558-4d0d-9ccf-dae10061b88f)

top box is speaker
bottom left box is robot starting position
bottom right box is robot shooting position

**Comment by Harsh-Sinha** [comment]
the above is for shoot on the move code... currently out of scope for robot
