### ISSUE TITLE
[Programming]Climber code

### ISSUE THREAD

**Issue by lethosor** [FRC830/2024Robot#24]

**Comment by lethosor** [comment]
Still need joystick code, testing

**Comment by nick-mcgill** [comment]
There are several compile errors in the [Climber](https://github.com/FRC830/2024Robot/tree/Climber) branch.

**Comment by nick-mcgill** [comment]
Created [climber-master-based](https://github.com/FRC830/2024Robot/tree/climber-master-based) which has the [master](https://github.com/FRC830/2024Robot/tree/master) branch and [Climber](https://github.com/FRC830/2024Robot/tree/Climber) branches merged together.  This branch currently builds, but needs additional work before being merged into master.

Work remaining: ClimberManager.cpp has a [FIXME tag](https://github.com/FRC830/2024Robot/blob/6dcae243ea6920072a1a5c4822be60961c00f47f/src/main/cpp/subsystems/subsystemManagers/ClimberManager.cpp#L10) noting where additional work needs to be performed.

**Comment by nick-mcgill** [comment]
Current step is utilizing the current state of **climber-master-based** branch to make the following changes:

1. Add the CAN IDs for the climber motors into the subsystemconfig.h file for consistency with the other motor IDs
2. Develop a logical limit (4 feet) for the climber to extend so we're within height restrictions

Recommendations for 2:

1. Utilize the encoder for the climber motors to determine # rotations
2. Identify height change per rotation
3. Calculate # rotations until we hit the height limit
4. Implement something that calculates height based on rotation state (we need to keep track of 
5. Implement something that prevents motor from rotating in the "up" direction when we've hit our max rotations

**Comment by nick-mcgill** [comment]
Branch has been updated with content of **master**.

Remaining work:
* Create controller input mapping
* Test on robot

**Comment by nick-mcgill** [comment]
Climber branch has been updated with content of master.

Remaining work:
* Merge into master
* Test on robot

@Harsh-Sinha [Draft PR created](https://github.com/FRC830/2024Robot/pull/19) for when branch is finalized.

CC @JoeyBrar @CanadaGoosee

**Comment by nick-mcgill** [comment]
Code is in review for the existing PR.  Harsh to provide final review, approval, and merge.

**Comment by nick-mcgill** [comment]
@Harsh-Sinha Please close this task after PR is merged to master.
