### ISSUE TITLE
[Programming]Test the current Launcher code

### ISSUE THREAD

**Issue by Harsh-Sinha** [FRC830/2024Robot#3]
Everything coded except for PID for flywheels and pivot

**Comment by lethosor** [comment]
in progress today including input code

**Comment by GrantR02** [comment]
Still needs the robot wired to test.

**Comment by nick-mcgill** [comment]
Launcher branch of code merged into master with #13.

**Comment by nick-mcgill** [comment]
This code has already been merged to master and should be testable on the robot.
